### ISSUE TITLE
Support for a "contains" TermClause

### ISSUE THREAD

**Issue by RalfG** [fastobo/fastobo-py#100]
When loading the [PSI-MOD.obo](https://raw.githubusercontent.com/HUPO-PSI/psi-mod-CV/master/PSI-MOD.obo) ontology, the following error is raised:
```
>>> obo_mod = fastobo.load("PSI-MOD.obo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5923
    contains: MOD:02026 ! S-(cysteinyl-glycyl)-L-cysteine␊
    ^
SyntaxError: expected EOI or TermClause
```
Seems like fastobo-py does not recognize the `contains` term. Can this term be added to the supported `TermClauses`, or is there a way for me to add support for it within my project?

**Comment by althonos** [comment]
Hi @RalfG ,

`fastobo` strives at compatibility with the [OBO 1.4 format version](http://owlcollab.github.io/oboformat/doc/obo-syntax.html), which does not consider `contains` a valid clause. 

Looking at the source file, it seems like the PSI team has been replacing these occurences within the OBO file; the expected format being:
```
relation: contains <term_id>
```
so I would expect this single clause to have gone under the radar; you should probably open a PR to https://github.com/HUPO-PSI/psi-mod-CV/

*on a sidenote, if you intend to do some high-level work on this ontology file with Python, I'd recommend using [`pronto`](https://github.com/althonos/pronto) instead, which uses `fastobo-py` for syntax but gives you easier access to the ontological data*

**Comment by RalfG** [comment]
Ok, thanks for the info!
