### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [fastobo/fastobo-py#245]
Problem
---------
On aarch64, ‘pip install fastobo’ build the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPi.

Resolution
-----------
On aarch64, ‘pip install fastobo’ should download the wheels from PyPi

@althonos, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by althonos** [comment]
I agree this would be a good thing to have. Rust builds are painfully slow, so the more available wheels, the better.

**Comment by althonos** [comment]
Thanks a lot for your PR!
