### ISSUE TITLE
Install fails on Python 3.11

### ISSUE THREAD

**Issue by joeflack4** [fastobo/fastobo-py#319]
## Overview
I am trying to `pip` install on Python 3.11, but I get an error.

## System
- OS: MacOS 11.4
- Architecture: x64
- Python: 3.11

### Short error
`  ERROR: Failed building wheel for fastobo`

### Log
`/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install fastobo -vv`:
[pipfail.txt](https://github.com/fastobo/fastobo-py/files/10170311/pipfail.txt)

**Comment by joeflack4** [comment]
@althonos My bad, shoulda done that. I updated the OP with system inversion and the full log with `-vv`.

**Comment by althonos** [comment]
Thanks! I have added Python 3.11 wheels for MacOS, could you try them out please? Try installing with `pip install fastobo --pre`.

**Comment by joeflack4** [comment]
Yay! `Successfully installed fastobo-0.12.2rc2`

That was fast, thanks a lot.

**Comment by althonos** [comment]
Happy to hear!
